### ISSUE TITLE
无法依赖：Unable to find a specification for 'optionSDK-iOS'.

### ISSUE THREAD

**Issue by Harry-III** [FotaPodRepo/optionSDK-iOS#1]
创建一个新的项目，设置好Podfile文件，可以引入MBProgressHUD库。但是无法引入本项目库，一直报错：Unable to find a specification for 'optionSDK-iOS'
Podfile文件中如下写着：
pod 'optionSDK-iOS', :git=>'https://github.com/FotaPodRepo/FotaPodRepo.git'

**Comment by storm52** [comment]
你的pod的写法有误，在pod中首行添加
source 'https://github.com/FotaPodRepo/FotaPodRepo.git'

然后添加
pod 'optionSDK-iOS'
